### ISSUE TITLE
Scheduling Tasks During a Task Doesn't Work

### ISSUE THREAD

**Issue by mkralka** [markkent/serial-executor-service#1]
When the executor is executing tasks (as a result of a call to `elapsedTime()`), any task that is scheduled from within one of those tasks has the duration passed to `elapsedTime()` subtracted from its delay.

Consider a task that is scheduled with a delay of 10s. When this task runs, it schedules another task with a delay of 20s. The first task should run a t=10s and the second task should run with t=30s. If `elapsedTime()` is first called with a duration of 15s, the first task is run and the second task is scheduled to run after 5s transpires (i.e., at t=20s). This is because the duration passed `elapsedTime()` (15s) is effectively subtracted from the scheduled task's duration (20s) before it is scheduled (leaving an effective delay of 5s).

**Comment by johngmyers** [comment]
Is this issue not fixed?

**Comment by mkralka** [comment]
Yes. Closed.
